services:
  - type: worker
    name: investfred-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_mejorado.py
    plan: free
    envVars:
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true